# Initial exports
export EDITOR="code -w"
export ZSH=$HOME/.dotfiles/.oh-my-zsh

# Auto-complete should be case-sensitive
CASE_SENSITIVE="true"

# Disable oh-my-zsh updates
DISABLE_AUTO_UPDATE="true"

fpath=(/usr/local/share/zsh-completions $fpath)

plugins=(bundler git heroku rails)

source $ZSH/oh-my-zsh.sh

# Prompt with git marker
PROMPT='%{$fg[cyan]%}%~ $(git_prompt_info)%{$reset_color%}$ '
PROMPT_EOL_MARK=""
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}("
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg[green]%}) "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}*"
ZSH_THEME_GIT_PROMPT_CLEAN=""

# Aliases
alias gcm='git commit -m'
compdef _git gcm=git-commit
alias code='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'

# Path
export PATH="$PATH:$HOME/.rvm/bin"
