# Initial exports
export EDITOR="code -w"
export ZSH=$HOME/.dotfiles/.oh-my-zsh

# Auto-complete should be case-sensitive
CASE_SENSITIVE="true"

# Disable oh-my-zsh updates
DISABLE_AUTO_UPDATE="true"

fpath=(/usr/local/share/zsh-completions $fpath)

plugins=(bundler git heroku rails)

source $ZSH/oh-my-zsh.sh

# Prompt with git marker
PROMPT='%{$fg[cyan]%}%~ $(git_prompt_info)%{$reset_color%}$ '
PROMPT_EOL_MARK=""
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}("
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$fg[green]%}) "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}*"
ZSH_THEME_GIT_PROMPT_CLEAN=""

# Aliases
alias gcm='git commit -m'
compdef _git gcm=git-commit
alias code='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'

# Env variables
export LOVEOS_BACKEND_AUTH_TOKEN=secret
export INTERNAL_CLIENT_AUTH_TOKEN=secret
export LOVEOS_BACKEND_HOST=127.0.0.1
export LOVEOS_BACKEND_PORT=7003

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
