export ZSH=/usr/local/opt/oh-my-zsh
export ZSH_CUSTOM=$HOME/.zsh-custom

# Auto-complete should be case-sensitive
CASE_SENSITIVE="true"

fpath=(/usr/local/share/zsh-completions $fpath)

plugins=(bundler chruby git heroku rails)

source $ZSH/oh-my-zsh.sh
